source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

def common
    pod 'Underscore.m', '~> 0.2.0'
    pod 'libextobjc', '~> 0.4.0'
end

target 'AMUIStylistExample' do
    common
    pod 'JRSwizzle', '~> 1.0'
end

target 'AMUIStylistExampleTests' do
    common
    pod 'Specta', '~> 1.0'
    pod 'Expecta', '~> 1.0'
    pod 'OCMockito', '~> 3.0'
end

